### PR TITLE
add person support to id lookup

### PR DESCRIPTION
**Pull request by tknorris**
This goes with the other PR to map tmdbs to better ids. Sometimes you get back a person that matched in tmdb

### CODE REVIEW

**Comment by razzeee** [comment]
This needs to go here: https://github.com/fuzeman/trakt.py

**Comment by tknorris** [comment]
got it, I'll close this one and submit it to fuzeman

**Comment by tknorris** [comment]
I just remembered that I don't actually have a project and/or fork for fuzeman's code. Can you submit the PR? If not, I can revert this commit and the other one that adds the id lookup in script.trakt. These commmits really are a waste of time. The chances of this issue actually occurring are minuscule. The only time this would be needed is if ALL of the following is true:
1.  The user has tv scrobble turned off.
2.  The user is playing media from an addon.
3.  The addon sets a script.trakt.ids parameter
4.  The id's parameter best_id result is a tmdb

Otherwise the logic I added would result in a trakt id, an imdb id, a tvdb id, or a slug being used all of which would work fine.

**Comment by razzeee** [comment]
Well, then let's not do that.

**Comment by tknorris** [comment]
ok, I'll revert my last two changes then to remove the id lookup. I'll fix it shortly.

**Pull request closed without merging**
